Consume K3d version v5.0.0 (#1026)
* increase minimum k3d version to v5.0.0

- adjust flags of 'kyma provision k3d' command to conform with version change
- add 'registry-use' flag to 'kyma provision k3d' to enable the user to
  bring it's own docker registry

* revert changes in coredns file

* apply suggested changes

* update k3s-arg flag

diff --git a/internal/k3d/mock/k3d b/internal/k3d/mock/k3d
--- a/internal/k3d/mock/k3d
+++ b/internal/k3d/mock/k3d
@@ -26,6 +26,34 @@ function version {
 }
 
 #
+# Mock for 'registry list' command
+#
+function registry_list {
+    dump_file registry_list.txt
+}
+
+#
+# Mock for 'registry list -o json' command
+#
+function registry_list_-o_json {
+    dump_file registry_list_exists.json
+}
+
+#
+# Mock for 'k3d registry create' command
+#
+function registry_create_kyma-registry_--port_5000 {
+    dump_file registry_create.txt
+}
+
+#
+# Mock for 'k3d registry delete' command
+#
+function registry_delete_k3d-kyma-registry {
+  dump_file registry_delete.txt
+}
+
+#
 # Mock for 'cluster list' command
 #
 function cluster_list {
@@ -42,7 +70,7 @@ function cluster_list_-o_json {
 #
 # Mock for 'k3d cluster create kyma' command
 #
-function cluster_create_kyma_--kubeconfig-update-default_--timeout_5s_--agents_1_--registry-create_--image_rancher/k3s:v1.20.7-k3s1_--k3s-server-arg_--disable_--k3s-server-arg_traefik_--k3s-server-arg_--alsologtostderr_--k3s-agent-arg_--no-rollback_-p_80:80@loadbalancer_-p_443:443@loadbalancer_--alsologtostderr {
+function cluster_create_kyma_--kubeconfig-update-default_--timeout_5s_--agents_1_--k3s-arg_--disable=traefik@server:0_--image_rancher/k3s:v1.20.7-k3s1_--registry-use_k3d-kyma-registry.localhost_--port_80:80@loadbalancer_--port_443:443@loadbalancer_--alsologtostderr {
     dump_file cluster_create.txt
 }
 
@@ -60,10 +88,9 @@ function cluster_delete_kyma {
 #
 function dump_file {
   local file=$1
-
   local fileAbs="$(dirname $0)/$file"
   if [ ! -f $fileAbs ]; then
-      >&2 echo "File '${file}' not found in k3s mock folder"
+      >&2 echo "File '${file}' not found in k3d mock folder"
       return 1
   fi
   cat $fileAbs
