Add further features for k3s provioning in CLI

diff --git a/internal/k3s/mock/k3d b/internal/k3s/mock/k3d
--- a/internal/k3s/mock/k3d
+++ b/internal/k3s/mock/k3d
@@ -2,81 +2,101 @@
 
 # Mock for simulating the k3d CLI tool.
 #
-# Provided CLI arguments are converted to function calls.
-# Example:
-# ./k3d version   =>   will trigger the function 'version'
+# Two mechanism are supported:
 #
-# Multiple arguments are concatenated by underscore (_).
-# Example:
-# ./k3d cluster list   =>   will trigger the function 'cluster_lister'
+# 1. Env-variable 'K3D_MOCK_DUMPFILE'
+#    Set the env-variable K3D_MOCK_DUMPFILE with a file name. File is expected in/under this mock-script directory.
+#    and the mock will simply dump the content of this file to STDOUT.
+#
+# 2. Call mock function
+#    This mechanism is only used if no env-var K3D_MOCK_DUMPFILE is defined.
+#    It maps the provided CLI arguments to a function call. Multiple arguments are concatenated by underscore (_).
+# 
+#    Example:
+#    ./k3d version        =>   will trigger the function 'version'
+#    ./k3d cluster list   =>   will trigger the function 'cluster_list'
+#
+
 
 #
 # Mock for 'version' command
 #
 function version {
-    echo  'k3d version v3.4.0
-k3s version v1.19.4-k3s1 (default)'
-    return 0
+    dump_file version.txt
 }
 
 #
 # Mock for 'help' command
 #
 function help {
-    echo 'https://k3d.io/
-k3d is a wrapper CLI that helps you to easily create k3s clusters inside docker.
-Nodes of a k3d cluster are docker containers running a k3s image.
-All Nodes of a k3d cluster are part of the same docker network.
-
-Usage:
-  k3d [flags]
-  k3d [command]
-
-Available Commands:
-  cluster     Manage cluster(s)
-  completion  Generate completion scripts for [bash, zsh, fish, powershell | psh]
-  help        Help about any command
-  image       Handle container images.
-  kubeconfig  Manage kubeconfig(s)
-  node        Manage node(s)
-  version     Show k3d and default k3s version
-
-Flags:
-  -h, --help      help for k3d
-      --trace     Enable super verbose output (trace logging)
-      --verbose   Enable verbose output (debug logging)
-      --version   Show k3d and default k3s version
-
-Use "k3d [command] --help" for more information about a command.'
+    dump_file help.txt
 }
 
 #
 # Mock for 'cluster list' command
 #
 function cluster_list {
-    echo 'NAME           SERVERS   AGENTS   LOADBALANCER
-kyma-cluster   1/1       0/0      true'
+    dump_file cluster_list.txt
 }
 
 #
-# Verify whether a mock function exists.
+# Mock for 'cluster list -o json' command
 #
-function fct_exists {
-    local mockFctName=$1
-    declare -f -F $mockFctName > /dev/null
-    return $?
+function cluster_list_-o_json {
+    dump_file cluster_list_empty.json
 }
 
-# Map CLI arguments to local function
-IFS='_'
-MOCK_FUNCTION="$*"
-IFS=' '
+#
+# Mock for 'cluster create' command
+#
+function cluster_create_kyma {
+    dump_file cluster_create.txt
+}
 
-fct_exists $MOCK_FUNCTION
-if [ $? -eq 0 ]; then
-  $MOCK_FUNCTION
+###########################
+
+#
+# Print file to stdout.
+#
+function dump_file {
+  local file=$1
+
+  local fileAbs="$(dirname $0)/$file"
+  if [ ! -f $fileAbs ]; then
+      >&2 echo "File '${file}' not found in k3s mock folder"
+      exit 2
+  fi
+  cat $fileAbs
   exit 0
+}
+
+#
+# Map CLI args to a mock function and call this function.
+#
+function call_mock_fct {
+    # Map CLI arguments to local function
+    IFS='_'
+    local mockFctName="$*"
+    IFS=' '
+
+    # Use 'declare' to verify whether a mock function exists
+    declare -f -F $mockFctName > /dev/null
+    if [ $? -eq 0 ]; then
+        $mockFctName
+        exit 0
+    else
+        >&2 echo "K3d mock-script doesn't include function '${mockFctName}'" 
+        exit 1
+    fi
+}
+
+# Do the job...
+
+if [ -n "$K3D_MOCK_DUMPFILE" ]; then
+    # If K3D_MOCK_DUMPFILE is defined, we simply dump the file (CLI args are ignored)
+    dump_file "$K3D_MOCK_DUMPFILE"
 else
-  echo "K3d mock-script doesn't include function '${MOCK_FUNCTION}'"
-  exit 1
+    # Call a mock function matching the CLI args
+    call_mock_fct $*
 fi
+
